package com.bilkent.erasmus.enums;

public enum ApplicationPoolType {

    APPLICATIONS_APPROVED,

    APPLICATIONS_REJECTED,

    APPLICATIONS_IN_WAITING_LIST,

    APPLICATIONS_CONFIRMED_BY_STUDENT,

    APPLICATIONS_DECLINED_BY_STUDENT

}
